name: Deploy Infrastructure

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Deploy MySQL Redis Nginx on EC2

      uses: appleboy/ssh-action@v1.0.3

      with:

        host: ${{ secrets.EC2_HOST }}

        username: ubuntu

        key: ${{ secrets.EC2_SSH_KEY }}


        script: |

          set -e

          echo "========== Deployment Started =========="


          if [ ! -d /opt/intbuddy/deployment/.git ]; then
            git clone https://github.com/AmarBhise97/IntBuddyDeployment.git /opt/intbuddy/deployment
          fi

          cd /opt/intbuddy/deployment


          echo "Pulling latest changes"

          git pull origin main



          echo "Creating Docker network"

          docker network create intbuddy-network || true



          echo "Deploying MySQL"

          cd mysql

          docker compose -f docker-compose.mysql.yml pull

          docker compose -f docker-compose.mysql.yml up -d



          echo "Deploying Redis"

          cd ../redis

          docker compose -f docker-compose.redis.yml pull

          docker compose -f docker-compose.redis.yml up -d



          echo "Deploying Nginx"

          cd ../nginx

          docker compose pull

          docker compose up -d --force-recreate



          echo "Checking running containers"

          docker ps



          echo "========== Deployment Completed =========="
